on:
  push:
    tags:
      - '**'

name: Publish
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
      - name: Build aar
        run: ./gradlew assembleRelease
      - name: Publish aar
        run: ./gradlew publish
        env:
          USER: ${GITHUB_ACTOR}
          PAT: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_VERSION: ${{ steps.get_version.outputs.VERSION }}